# Pull base image
FROM python:3.13-slim-trixie

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# PostgreSQL クライアントをインストール（pg_isreadyが含まれる）
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Copy only requirements to leverage Docker caching
COPY backend/requirements requirements

# Install dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements/dev.txt

# Copy project
COPY backend/ .

# Copy entrypoint.sh to a fixed location
COPY docker/backend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh